[package]
name = "space_email_api"
version = "0.1.2"
authors = ["AlphaModder"]
description = "A rust interface to Space Email (space.galaxybuster.net)"
license = "MIT"

[dependencies]
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
chrono = "0.3"
regex = "0.2"
serde_json = "0.9.10"
select = "0.4.0"
url = "1.4.0"
lazy_static = "0.2"